-- AlterTable
ALTER TABLE `Extraccion` ADD COLUMN `tipoOperacionOld` ENUM('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'DEBITO_AUTOMATICO_TARJETA_CREDITO') NOT NULL DEFAULT 'EFECTIVO';

-- AlterTable
ALTER TABLE `Gasto` ADD COLUMN `tipoOperacionOld` ENUM('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'DEBITO_AUTOMATICO_TARJETA_CREDITO') NOT NULL DEFAULT 'EFECTIVO';

-- AlterTable
ALTER TABLE `IngresoManualDeDinero` ADD COLUMN `tipoOperacionOld` ENUM('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'DEBITO_AUTOMATICO_TARJETA_CREDITO') NOT NULL DEFAULT 'EFECTIVO';

-- AlterTable
ALTER TABLE `IngresoPorReparacion` ADD COLUMN `tipoOperacionOld` ENUM('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'DEBITO_AUTOMATICO_TARJETA_CREDITO') NOT NULL DEFAULT 'EFECTIVO';

-- AlterTable
ALTER TABLE `Venta` ADD COLUMN `tipoOperacionOld` ENUM('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'DEBITO_AUTOMATICO_TARJETA_CREDITO') NOT NULL DEFAULT 'EFECTIVO';
